version: "3.5"
services:
  minio:
    image: 'minio/minio:latest'
    container_name: minio
    ports:
      - '8000:8000'
      - '8001:8001'
    volumes:
      - './minio-data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio1234
    command: server /data -address :8000 -console-address :8001

volumes:
  minio-data:
